#!/bin/sh

# setup environment
OLD_PATH=$(pwd)
cd $(dirname $0)
export AXT_PATH=$(pwd)
cd ${OLD_PATH}


# process subcommand
SUBCOMMAND=$1
shift

if [[ -z $SUBCOMMAND ]]; then
    SUBCOMMAND="help"
fi

# source ~/.axtrc
export AXT_RC="${HOME}/.axtrc"

if [ -f ${AXT_RC} ]; then
	source ${AXT_RC}
elif [ "$SUBCOMMAND" != "setup" ] && [ "$SUBCOMMAND" != "help" ]; then
	echo >&2 "AXT ERROR: ~/.axtrc does not exist, run axt setup!"
	exit 
fi


# check installed helpers
command -v peco  >/dev/null 2>&1 || { echo >&2 "AXT WARNING: AXT requires helper 'peco'. Some subcommands might not work without it!"; }


# execute full command
COMMAND="axt-${SUBCOMMAND}.sh"
FULL_COMMAND=$(find ${AXT_PATH} -name ${COMMAND} -print)

if [[ ${FULL_COMMAND} ]]; then
	eval "${FULL_COMMAND} $@"
else
	echo "axt: Unknown command '${SUBCOMMAND}'"
fi
