#!/bin/sh

# setup environment
OLD_PATH=$(pwd)
cd $(dirname $0)
export AXT_PATH=$(pwd)
cd ${OLD_PATH}


# check installed helpers
command -v peco  >/dev/null 2>&1 || { echo >&2 "AXT WARNING: AXT requires helper 'peco'. Some subcommands might not work without it!"; }


# source .axtrc's
AXT_RCS=$(find ${AXT_PATH} -name .axtrc -print)
for AXT_RC in ${AXT_RCS[@]}; do
	source ${AXT_RC}
done


# process subcommand
SUBCOMMAND=$1
shift

if [[ -z $SUBCOMMAND ]]; then
    SUBCOMMAND="help"
fi


# execute full command
COMMAND="axt-${SUBCOMMAND}.sh"
FULL_COMMAND=$(find ${AXT_PATH} -name ${COMMAND} -print)

if [[ ${FULL_COMMAND} ]]; then
	eval "${FULL_COMMAND} $@"
else
	echo "axt: Unknown command '${SUBCOMMAND}'"
fi
