#!/bin/sh

# setup environment
cd $(dirname $0)
export AXT_PATH=$(pwd)

# source .axtrc's
AXT_RCS=$(find ${AXTPATH} -name .axtrc -print)
for AXT_RC in "${AXT_RCS[@]}"; do
	source ${AXT_RC}
done

# process subcommand
SUBCOMMAND=$1
shift

if [[ -z $SUBCOMMAND ]]; then
    SUBCOMMAND="help"
fi

# execute full command
COMMAND="axt-${SUBCOMMAND}.sh"
FULL_COMMAND=$(find ${AXTPATH} -name ${COMMAND} -print)

if [[ ${FULL_COMMAND} ]]; then
	eval "${FULL_COMMAND} $@"
else
	echo "axt: Unknown command '${SUBCOMMAND}'"
fi

