#!/bin/sh

# HELP: <add short help text (one line)>
# USAGE: <add usage in format axt <command> ... if your command needs paramters. Otherwise, delete this line>

# check if we're in AXT environment
if [[ ! -v AXT_PATH ]] || [ -z "${AXT_PATH}" ]; then
	echo >&2 "AXT ERROR: Please execute $0 from axt"
	exit
fi
test -v AXT_XXX || echo >&2 "AXT ERROR: \$AXT_XXX not set, run 'axt setup'"; exit


<YOUR CODE GOES HERE>